version: '3'

services:
  service1:
    build: ./service1
    container_name: 21je0702-service1
    restart: always

  service2:
    build: ./service2
    container_name: 21je0702-service2
    restart: always

  haproxy:
    build: ./haproxy
    container_name: haproxy
    restart: always
    ports:
      - "80:80"
    depends_on:
      - service1
      - service2
